# Generated by Django 4.0.3 on 2022-07-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0003_alter_bookmark_id_alter_pinnedapplication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pinnedapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
