# Generated by Django 4.0.4 on 2022-09-23 18:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('users', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('api_hash', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('phone_code_hash', models.CharField(max_length=255)),
                ('phone_code', models.CharField(max_length=255)),
            ],
        ),
    ]
