# Generated by Django 4.0.4 on 2022-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_telegramuser_phone_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
