# Generated by Django 4.0.3 on 2022-10-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tarrif'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Неизвестно'), (1, 'Работает'), (2, 'Не работает')], default=0),
        ),
    ]
