# Generated by Django 4.0.3 on 2022-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_telegramuser_ok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Телеграм аккаунт', 'verbose_name_plural': 'Телеграм аккаунты'},
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='ok',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='phone_code_hash',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='session_string',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
