# Generated by Django 4.0.3 on 2022-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'История покупок'},
        ),
        migrations.AddField(
            model_name='user',
            name='available_messages_count',
            field=models.IntegerField(default=10),
        ),
    ]
