# Generated by Django 4.0.3 on 2022-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_telegramuser_session_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='session_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
