# Generated by Django 4.0.3 on 2022-10-02 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_purchase_options_user_available_messages_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='PurchaseTarrif',
        ),
        migrations.AlterModelOptions(
            name='purchasetarrif',
            options={'verbose_name': 'Покупка тарифа', 'verbose_name_plural': 'Покупки тарифа'},
        ),
        migrations.CreateModel(
            name='BalanceReplenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_replenishments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
