# Generated by Django 3.2.10 on 2022-10-04 23:07

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_mailing_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.avatar_directory_path),
        ),
    ]
