# Generated by Django 4.1.2 on 2022-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_mailing_image_parseredchat_chatmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parseredchat',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
