# Generated by Django 4.1.2 on 2022-10-10 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_parseredchat_options_mailing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'В работе'), (2, 'Завершен')], default=2),
        ),
    ]
